config/routes.rb
Rails.application.routes.draw do
  resources :groups, only: [:index, :show, :new, :create]
  resources :records
  get 'profile/:id', to: 'users#show', as: 'profile'
  post 'registration', to: 'users#create'
  get 'registration', to: 'users#new'
  get 'profile/edit/:id', to: 'users#edit', as: 'profile_edit'
  patch 'profile/update/:id', to: 'users#update', as: 'profile_update'
  get 'login', to: 'static_pages#login'
  post 'login', to: 'static_pages#create_login'
  delete 'logout', to: 'static_pages#logout'
  get 'dashboard', to: 'static_pages#dashboard'
  get 'allrecords', to: 'records#allmyrecords'
  get 'allexternalrecords', to: 'records#allmyexternalrecords'
  root 'static_pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  mount_uploader :icon, IconUploader
  validates :name, presence: true, uniqueness: true
  validates :user_id, presence: true
  validates :icon, presence: true
  belongs_to :user
  has_many :records
  scope :order_group, ->(ord) { order(name: ord) }
end

app/models/record.rb
class Record < ApplicationRecord
  validates :name, presence: true
  validates :authorid, presence: true
  validates :minutes, presence: true
  belongs_to :author, class_name: 'User', foreign_key: 'authorid'
  belongs_to :group, optional: true
  scope :grouped, -> { where.not(group_id: nil) }
  scope :not_grouped, -> { where(group_id: nil) }
  scope :mine, ->(user_id) { where(authorid: user_id) }
  scope :order_record, ->(ord) { order(updated_at: ord) }
  scope :all_my_total, ->(user, ord = 'desc') { Record.mine(user).includes(:group).order_record(ord) }
  scope :all_my_records, ->(user, ord = 'desc') { Record.mine(user).grouped.includes(:group).order_record(ord) }
  scope :all_my_external, ->(user, ord = 'desc') { Record.mine(user).not_grouped.includes(:group).order_record(ord) }
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  before_save :remove_whitespaces_downcases
  before_validation :remove_whitespaces_downcases
  validates :name, presence: true, length: { maximum: 100 }
  validates :username, presence: true, uniqueness: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
  validates :email, length: { maximum: 200 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: true
  has_many :groups
  has_many :records, foreign_key: 'authorid'

  private

  def remove_whitespaces_downcases
    self.email = email.strip
    self.username = username.strip.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include StaticPagesHelper
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :logged_in_user
  before_action :set_group, only: [:show]

  def index
    @groups = if params[:sort] == 'asc' || params[:sort] == 'desc'
                Group.all.includes(:user).order_group(params[:sort])
              else
                Group.all.includes(:user)
              end
  end

  def new
    @group = Group.new
  end

  def show; end

  def create
    @group = Group.new(group_params)
    @group.user_id = current_user.id
    if @group.save
      flash[:success] = 'Program created successfully'
      redirect_to groups_path
    else
      render :new
    end
  end

  private

  def group_params
    params.require(:group).permit(:user_id, :name, :icon, :icon_cache)
  end

  def set_group
    @group = Group.includes(records: :author).find(params[:id])
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :logged_in_user
  before_action :set_record, only: %i[show edit update destroy]

  def index
    @records = if params[:sort] == 'asc' || params[:sort] == 'desc'
                 Record.includes(:group).includes(:author).all.order_record(params[:sort])
               else
                 Record.includes(:group).includes(:author).all
               end
  end

  def allmyrecords
    @records = if params[:sort] == 'asc' || params[:sort] == 'desc'
                 Record.all_my_records(current_user, params[:sort])
               else
                 Record.all_my_records(current_user)
               end
  end

  def allmyexternalrecords
    @records = if params[:sort] == 'asc' || params[:sort] == 'desc'
                 Record.all_my_external(current_user, params[:sort])
               else
                 Record.all_my_external(current_user)
               end
  end

  def show; end

  def new
    @record = Record.new
  end

  def create
    @record = Record.new(record_params)
    @record.authorid = @current_user.id
    if @record.save
      flash[:success] = 'Record created successfully'
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @record.update(record_params)
      flash[:success] = 'Record updated successfully'
      render :show
    else
      render :edit
    end
  end

  def destroy
    if @record.destroy
      flash[:success] = 'Record deleted successfully'
      redirect_to dashboard_path
    else
      flash[:danger] = 'Something is wrong, try again later'
      redirect_to record_path(params[:id])
    end
  end

  private

  def set_record
    @record = Record.find(params[:id])
  end

  def record_params
    params.require(:record).permit(:name, :authorid, :minutes, :group_id)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :logged_in_user, only: [:dashboard]
  def index; end

  def login; end

  def create_login
    email_user = params[:email].strip.downcase
    if (@user = User.find_by(email: email_user))
      login_user(@user)
      redirect_to dashboard_path
    else
      flash[:error] = "User doesn't exist"
      redirect_to login_path
    end
  end

  def logout
    logout_user
    redirect_to root_path
  end

  def dashboard
    @allmyrecords = Record.all_my_total(current_user, 'desc')
    @hash = Record.mine(current_user).joins(:group).group('groups.name').sum('minutes')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: %i[show edit update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login_user(@user)
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      flash[:success] = 'User updated successfully'
      redirect_to profile_path(current_user)
    else
      render :edit
    end
  end

  private

  def correct_user
    @user = User.find(params[:id])
    redirect_to dashboard_path unless current_user?(@user)
  end

  def user_params
    params.require(:user).permit(:name, :email, :username, :avatar, :avatar_cache)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bs_class_for(flash_type)
    case flash_type
    when 'success'
      'alert-success'
    when 'error', 'danger'
      'alert-danger'
    when 'notice'
      'alert-info'
    else
      flash_type.to_s
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  def login_user(user)
    session[:current_user] = user.id
    current_user
  end

  def logout_user
    session.delete(:current_user)
    @current_user = nil
  end

  def current_user
    @current_user ||= User.find_by(id: session[:current_user]) if session[:current_user]
  end

  def current_user?(user)
    user && user == current_user
  end

  def logged_in?
    !current_user.nil?
  end

  def logged_in_user
    return if logged_in?

    flash[:danger] = 'Please log in.'
    redirect_to login_url
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/index.html.erb
<div class="nav-scroller bg-white shadow-sm justify-content-around d-flex">
  <nav class="nav nav-underline">
    <%= link_to({ sort: :asc }, class:'nav-link') do %>
      Order by [A-Z]
      <span class="badge badge-pill bg-light align-text-bottom"><%= @groups.where(created_at: Date.today.all_day).count %></span>
      <i class="fas fa-sort-amount-up-alt"></i>
    <% end %>
    <%= link_to({ sort: :desc }, class:'nav-link') do %>
      Order by [Z-A]
      <span class="badge badge-pill bg-light align-text-bottom"><%= @groups.count - @groups.where(created_at: Date.today.all_day).count %></span>
      <i class="fas fa-sort-amount-down-alt"></i>
    <% end %>
  </nav>
</div>
<h1 class="text-center mt-3">All Programs & Shows</h1>
<%= link_to "Add new Program", new_group_path, class: 'btn btn-success btn-block' %>
<br>
<hr>
<div class="programs-container">
    <% @groups.each do |group| %>
        <div class="program-single d-flex align-items-center">
            <div class="img-container">
                <% if group.icon.thumb.url %>
                    <%= image_tag group.icon.thumb.url, class: 'img img-fluid', alt: group.name %>
                <% end %>
            </div>
            <div class="text ml-1">
                <p class="h2"><%= group.name %></p>
                <p class="text-muted mb-0"><strong>Created:</strong><%= localize(group.created_at, format: :sample) %></p>
                <p class="text-muted mb-0"><strong>Created by: @</strong><%= group.user.username %></p>
            </div>
        </div>
        <%= link_to "See program", group_path(group), class: 'btn btn-primary_accent btn-block text-light mt-3' %>
        <hr>
    <% end %>
</div>

app/views/groups/new.html.erb
<h2 class="text-center mt-3">Add your favorite program or show</h2>
<%= form_with(model: @group, local:true, html: { multipart: true }) do |form| %>
    <% if @group.errors.any? %>
    <div id="error_explanation">
        <ul>
            <% @group.errors.full_messages.each do |message| %>
                <li class="text-danger"><%= message %></li>
            <% end %>
        </ul>
    </div>
    <% end %>

    <div class="form-group field">
        <%= form.label :name %>
        <%= form.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group field">
        <%= form.label :icon %>
        <%= form.file_field :icon, class: 'form-control-file' %>
        <%= form.hidden_field :icon_cache %>
    </div>

    <div class="actions">
        <%= form.submit class: 'btn btn-success btn-block'%>
    </div>
<% end %>

app/views/groups/show.html.erb
<h2 class="mt-3 text-center"><%= @group.name.upcase %></h2>
<% if @group.icon.url%>
    <%= image_tag @group.icon.url, class: 'img img-fluid', alt: @group.name %>
<% end %>
<br>
<p class="h3 mt-3">Records of this show:</p>
<hr>
<div class="records-container">
    <% @group.records.each do |record| %>
        <span class="d-block"><strong><%= record.name %></strong></span>
        <span class="text-muted d-block">by: @<%= record.author.username %></span>
        <span class="d-block text-muted">Created <%= time_ago_in_words(record.created_at) %> ago</span>
        <hr>
    <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-xl fixed-top navbar-dark bg-primary">
  <div class="w-100 d-flex justify-content-between">
      <div>
          <button class="navbar-toggler p-0 border-0" type="button" onclick="mytoggler()">
            <span class="navbar-toggler-icon"></span>
          </button>
      </div>
      <div>
        <a class="navbar-brand mr-auto mr-lg-0 f-gochi" href="<%= dashboard_path %>">Lakastapp!</a>
      </div>
      <div class="d-hidden">
        
      </div>
  </div>

  <div class="navbar-collapse offcanvas-collapse" id="navbarDefault">
    <ul class="navbar-nav mr-auto">
    <% if logged_in? %>
      <li class="p-2">
        <a href="<%= dashboard_path %>">
          <% if !current_user.avatar.thumb.url.nil? %>
            <%= image_tag current_user.avatar.thumb.url, class: 'img img-fluid rounded-circle', alt: current_user.name %>
          <% else %>
            <%= image_tag 'avatarthumb.png', class: 'img img-fluid rounded-circle', alt: 'default avatar' %>
          <% end %>
          <%= content_tag :span, current_user.name, class: 'nav-link active' %>
        </a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="<%= profile_path(current_user) %>">My profile <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <%= link_to "All my records", allrecords_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "All my external records", allexternalrecords_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "All Programs & Shows", groups_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "Log Out", logout_path, class: 'nav-link', method: 'delete' %>
      </li>
    <% else %>
      <li class="nav-item">
        <%= link_to "Register", registration_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Log In', login_path, class: "nav-link" %>
      </li>
    <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lakastapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
    <% flash.each do |name, msg| %>
      <div class="alert <%= bs_class_for(name) %> fade_in">
        <button class="close" data-dismiss="alert">x</button>
        <%= msg %>
      </div>
    <% end %>
    <main class="container">
      <%= yield %>
    </main>
    <script>
      function mytoggler() {
        let elem = document.getElementById("navbarDefault");
        elem.classList.toggle("open");
      }
    </script>
  </body>
</html>

app/views/records/_form.html.erb
<%= form_with(model: record, local: true) do |form| %>
    <% if record.errors.any? %>
    <div id="error_explanation">
        <ul>
            <% record.errors.full_messages.each do |message| %>
                <li class="text-danger"><%= message %></li>
            <% end %>
        </ul>
    </div>
    <% end %>

    <div class="form-group field">
        <%= form.label :name %>
        <%= form.text_field :name ,class: "form-control" %>
    </div>

    <div class="form-group field">
        <%= form.label :minutes %>
        <%= form.number_field :minutes, class: "form-control" %>
    </div>

    <div class="input-group mb-3 field">
        <div class="input-group-prepend">
            <%= form.label :group_id, class:'input-group-text' %>
        </div>
        <%= form.collection_select :group_id, Group.all, :id, :name, { prompt: true }, { class: 'custom-select' } %>
    </div>

    <div class="actions">
        <%= form.submit class: 'btn btn-success btn-block' %>
    </div>
<% end %>

app/views/records/_records.html.erb
<div class="nav-scroller bg-white shadow-sm justify-content-around d-flex">
  <nav class="nav nav-underline">
    <%= link_to({ sort: :desc }, class:'nav-link') do %>
        Most Recent
        <span class="badge badge-pill bg-light align-text-bottom"><%= records.where(created_at: Date.today.all_day).count %></span>
        <i class="fas fa-sort-amount-up-alt"></i>
    <% end %>
    <%= link_to({ sort: :asc }, class:'nav-link') do %>
        Most Ancient
        <span class="badge badge-pill bg-light align-text-bottom"><%= records.count - records.where(created_at: Date.today.all_day).count %></span>
        <i class="fas fa-sort-amount-down-alt"></i>
    <% end %>
  </nav>
</div>

<h2>All Records</h2>
<%= link_to "Add new Record", new_record_path, class: 'btn btn-success btn-block' %>
<hr>
<h4 class="d-flex justify-content-end text-muted">Total minutes:&nbsp;<strong class="text-info"><%= records.sum(:minutes) %></strong></h4>
<hr>
<% if external %>
    <div class="external-container">
<% else %>
    <div class="no-external-container">
<% end %>
<% records.each do |record| %>
    <div class="record-container d-flex align-items-center d-flex justify-content-between">
        <div class="img-record">
            <% unless external %>
                <% if record.group.icon.url%>
                    <%= image_tag record.group.icon.thumb.url, class: 'img img-fluid' %>
                <% end %>
            <% end %>
        </div>
        <div class="text-record">
            <p class="h6 m-0"><%= record.name %></p>
            <p class="h6 m-0 text-muted"><%= current_user.name %></p>
            <p class="h6 m-0 text-muted">@<%= current_user.username %></p>
            <p class="h6 m-0"><%= localize(record.created_at, format: :sample) %></p>
        </div>
        <div class="minutes-record text-right">
            <h5 class="text-muted m-0"><strong class="text-info"><%= record.minutes %></strong> minutes.</h5>
        </div>
            <!--<%= link_to 'Delete', record, method: 'delete', class: 'btn btn-danger', data: { confirm: 'Are you sure?' } %>-->
    </div>
    <%= link_to "See Details", record_path(record), class: 'btn btn-primary_accent btn-block mt-3' %>
    <hr>
<% end %>
</div>

app/views/records/allmyexternalrecords.html.erb
<%= render 'records', records: @records, external: true %>

app/views/records/allmyrecords.html.erb
<%= render 'records', records: @records, external: false %>

app/views/records/edit.html.erb
<h2 class="mt-3">Edit Record</h2>
<%= render 'form', record: @record %>

app/views/records/index.html.erb
<div class="nav-scroller bg-white shadow-sm justify-content-around d-flex">
  <nav class="nav nav-underline">
    <%= link_to({ sort: :desc }, class:'nav-link') do %>
      Most Recent
      <span class="badge badge-pill bg-light align-text-bottom"><%= @records.where(created_at: Date.today.all_day).count %></span>
      <i class="fas fa-sort-amount-up-alt"></i>
    <% end %>
    <%= link_to({ sort: :asc }, class:'nav-link') do %>
      Most Ancient
      <span class="badge badge-pill bg-light align-text-bottom"><%= @records.count - @records.where(created_at: Date.today.all_day).count %></span>
      <i class="fas fa-sort-amount-down-alt"></i>
    <% end %>
  </nav>
</div>

<h1>Total Records</h1>
<%= link_to "Add new Record", new_record_path, class: 'btn btn-success btn-block' %>
<hr>
<h4 class="d-flex justify-content-end text-muted">Total minutes:&nbsp;<strong class="text-info"><%= @records.sum(:minutes) %></strong></h4>
<hr>
<div class="no-external-container">
<% @records.each do |record| %>
    <div class="record-container d-flex align-items-center d-flex justify-content-between">
      <div class="img-record">
        <% if !record.group.nil? && !record.group.icon.url.nil? %>
          <% if record.group.icon.url %>
            <%= image_tag record.group.icon.thumb.url, class: 'img img-fluid' %>
          <% end %>
        <% end %>
      </div>
      <div class="text-record">
        <p class="h6 m-0"><%= record.name %></p>
        <p class="h6 m-0 text-muted"><%= record.author.name %></p>
        <p class="h6 m-0 text-muted">@<%= record.author.username %></p>
        <p class="h6 m-0"><%= localize(record.created_at, format: :sample) %></p>
      </div>
      <div class="minutes-record text-right">
        <h5 class="text-muted m-0"><strong class="text-info"><%= record.minutes %></strong> minutes.</h5>
      </div>
    </div>
    <%= link_to "See details", record_path(record), class: 'btn btn-primary_accent btn-block mt-3' %>
    <hr>
<% end %>
</div>

app/views/records/new.html.erb
<h2 class="mt-3">New Record</h2>
<%= render 'form', record: @record %>

app/views/records/show.html.erb
<h2 class="mt-3">Record Details:</h2>
<div class="record-container d-flex align-items-center">
    <div class="record-text">
        <h3><%= @record.name %></h3>
        <p class="h4"><strong><%= @record.minutes %></strong> Minutes</p>
        <p class="text-muted mb-0">By: @<%= @record.author.username %></p>
    </div>
    <div class="record-actions">
        <%= link_to 'Edit', edit_record_path(@record), class: 'btn btn-warning btn-block' %>
        <%= link_to 'Delete', @record, method: 'delete', class: 'btn btn-danger btn-block', data: { confirm: 'Are you sure?' } %>
    </div>
</div>
<hr>
<% if !@record.group.nil? && @record.group.icon.url %>
    <h3 class="text-center"><%= @record.group.name %></h3>
    <%= image_tag @record.group.icon.url, class: 'img img-fluid' %>
<% end %>

app/views/static_pages/dashboard.html.erb
<div class="pt-2 d-flex">
    <% if !current_user.avatar.thumb.url.nil? %>
        <%= image_tag current_user.avatar.thumb.url, class: 'img-fluid rounded-circle float-left' %>
    <% else %>
        <%= image_tag 'avatarthumb.png', class: 'img img-fluid rounded-circle'%>
    <% end %>
    <div class="d-flex align-items-start flex-column mt-3">
        <%= content_tag :span, current_user.name, class: 'h4' %>
        <%= content_tag(:span, "@#{current_user.username}", class: 'text-muted') %>
    </div>
</div>
<div class="row text-center">
    <div class="row viewed-hours p-2 text-light rounded m-3 align-items-center">
        <i class="fas fa-eye fa-2x text-light position-absolute"></i>
            <div class="col-12">Total viewed minutes:</div>
            <div class="col-12 h2">
            <%= @allmyrecords.sum(:minutes) %>
            </div>
    </div>
    <div class="most-viewed p-2 text-light rounded m-3">
        <div>Most viewed show:</div>
        <% if !@hash.empty? %>
            <div class="h3"><%= @hash.key(@hash.values.max) %></div>
            <div><%= "With " + @hash.values.max.to_s + " total minutes"%></div>
        <% else %>
            <div>No Enough Data</div>
        <% end %>
    </div>
    <div class="row total-created p-2 text-light rounded m-3 align-items-center">
    <i class="fas fa-edit fa-2x text-light position-absolute"></i>
        <div class="col-12">Total records created</div>
        <div class="h2 col-12"><%= @allmyrecords.count %></div>
    </div>
    <div class="last-viewed p-2 text-light rounded m-3">
        <div>Last show viewed</div>
        <% if !@allmyrecords.first.nil? && !@allmyrecords.first.group.nil? %>
            <div class="h3">
                <%= @allmyrecords.first.group.name %>
            </div>
            <div>
                <%= time_ago_in_words(@allmyrecords.first.created_at) + " ago"%>
            </div>
        <% else %>
            <div>
                No Enough Data
            </div>
        <% end %>
    </div>
</div>

app/views/static_pages/index.html.erb
<div class="text-center">
  <h1 class="cover-heading f-gochi p-3">LAKASTAPP!</h1>
  <p class="lead">If you love to watch online series and programs, Lakastapp is for you!</p>
  <p class="lead">With Lakastapp you can keep a record of every program you watch!</p>
  <p class="lead">Come on! It's free!</p>
  <hr>
  <%= link_to 'Log In', login_path, class:'btn btn-lg btn-primary_accent btn-block' %>
  <a href="<%= registration_path %>" class="btn btn-lg btn-primary_shades btn-block">Sign up</a>
  <hr>
</div>

app/views/static_pages/login.html.erb
<h2 class="col-sm-8 m-auto py-3 text-center">Please log in: </h2>
  <div class= "col-sm-10 m-auto ">
    <%= form_with url: login_path do |f| %>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email, class:'form-control', required: true %>
      </div>
      <%= f.submit 'Log In', class: 'btn btn-primary_accent btn-block' %>
    <% end %>
  </div>

app/views/users/_form.html.erb
<%= form_with model: user, url: update ? profile_update_path : registration_path, local:true do |f| %>
    <% if user.errors.any? %>
    <div id="error_explanation">
        <ul>
            <% user.errors.full_messages.each do |message| %>
            <li class="text-danger"><%= message %></li>
            <% end %>
        </ul>
    </div>
    <% end %>
    <div class="form-group field">
        <%= f.label :name %>
        <%= f.text_field :name, class:'form-control' %>
    </div>
    <div class="form-group field">
        <%= f.label :username %>
        <%= f.text_field :username, class:'form-control' %>
    </div>
    <div class="form-group field">
        <%= f.label :email %>
        <%= f.text_field :email, class:'form-control' %>
    </div>
    <div class="form-group field">
        <% btnstr = 'Create Account' %>
        <%= f.label :avatar, class: 'mr-2' %>
        <% if update %>
            <% btnstr = 'Update Profile' %>
            <% if !@user.avatar.url.nil? %>
                <%= image_tag @user.avatar.thumb.url, class: 'img img-fluid mb-2', alt: @user.name %>
            <% else %>
                <%= image_tag 'avatarthumb.png', class: "img img-fluid mb-2", alt: 'default avatar' %>
            <% end %>
        <% end %>
        <%= f.file_field :avatar, class: 'form-control-file' %>
        <%= f.hidden_field :avatar_cache %>
    </div>
    <div class="actions">
        <%= f.submit btnstr, class: 'btn btn-primary_accent btn-block' %>
    </div>
<% end %>

app/views/users/edit.html.erb
<h2 class="col-sm-10 m-auto py-3">Update your account!</h2>
  <div class= "col-sm-10 m-auto ">
    <%= render 'form', user: @user, update: true %>
  </div>

app/views/users/new.html.erb
<h2 class="col-sm-10 m-auto py-3 text-center">Create your account!</h2>
<div class= "col-sm-10 m-auto ">
  <%= render 'form', user: @user, update: false %>
</div>

app/views/users/show.html.erb
<h2 class="mt-3"><%= @user.name %></h2>
<h4 class="text-muted mb-0">@<%= @user.username %></h4>
<h4 class="text-muted mb-0"><%= @user.email %></h4>
<p>Created <%= time_ago_in_words(@user.created_at) %> ago</p>
<h5>Avatar: </h5>
<% if @user.avatar.url %>
    <%= image_tag @user.avatar.url, class: 'img img-fluid', alt: @user.name %>
<% else %>
    <%= image_tag 'avatar500.png', class: "img img-fluid", alt: 'default avatar' %>
<% end %>
<br>
<%= link_to "Edit my profile", profile_edit_path(current_user), class: 'btn btn-warning btn-block mt-3' %>